import { Work_Sans } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/contexts/GlobalProvider";

// Load Google Font
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["500", "100", "200", "300", "400", "600", "700", "800", "900"], // Only load 800 weight
});

export const metadata = {
  title: "CPMK",
  description: "Generated by MEG Industries &copy; 2025",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`border- ${workSans.className} antialiased w-full`}
      >
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
